import { sub } from 'date-fns'

const mails = [{
  id: 1,
  name: 'محمدي خيري',
  phone: '01021269329',
  email: 'm@m.com',
  image: { src: 'https://i.pravatar.cc/128?u=1' },
  grade_level: 'الصف الثالث الثانوي',
  gender: 'ذكر',
  school_name: 'السادات',
  parent_name: 'عبدالسلام خيري',
  course_name: 'العربي',
  date: new Date().toISOString()
},
{
  id: 2,
  name: 'محمدي خيري',
  phone: '01021269329',
  email: 'm@m.com',
  image: { src: 'https://i.pravatar.cc/128?u=1' },
  grade_level: 'الصف الثالث الثانوي',
  gender: 'ذكر',
  school_name: 'السادات',
  parent_name: 'عبدالسلام خيري',
  course_name: 'العربي',
  date: new Date().toISOString(),
  unread: true
},
{
  id: 3,
  name: 'محمدي خيري',
  phone: '01021269329',
  email: 'm@m.com',
  image: { src: 'https://i.pravatar.cc/128?u=1' },
  grade_level: 'الصف الثالث الثانوي',
  gender: 'ذكر',
  school_name: 'السادات',
  parent_name: 'عبدالسلام خيري',
  course_name: 'العربي',
  date: new Date().toISOString(),
  unread: true
},
{
  id: 4,
  name: 'محمدي خيري',
  phone: '01021269329',
  email: 'm@m.com',
  image: { src: 'https://i.pravatar.cc/128?u=1' },
  grade_level: 'الصف الثالث الثانوي',
  gender: 'ذكر',
  school_name: 'السادات',
  parent_name: 'عبدالسلام خيري',
  course_name: 'العربي',
  date: new Date().toISOString(),
  unread: true
},
{
  id: 5,
  name: 'محمدي خيري',
  phone: '01021269329',
  email: 'm@m.com',
  image: { src: 'https://i.pravatar.cc/128?u=1' },
  grade_level: 'الصف الثالث الثانوي',
  gender: 'ذكر',
  school_name: 'السادات',
  parent_name: 'عبدالسلام خيري',
  course_name: 'العربي',
  date: new Date().toISOString(),
  unread: true
},
{
  id: 6,
  name: 'محمدي خيري',
  phone: '01021269329',
  email: 'm@m.com',
  image: { src: 'https://i.pravatar.cc/128?u=1' },
  grade_level: 'الصف الثالث الثانوي',
  gender: 'ذكر',
  school_name: 'السادات',
  parent_name: 'عبدالسلام خيري',
  course_name: 'العربي',
  date: new Date().toISOString(),
  unread: true
},
{
  id: 7,
  name: 'محمدي خيري',
  phone: '01021269329',
  email: 'm@m.com',
  image: { src: 'https://i.pravatar.cc/128?u=1' },
  grade_level: 'الصف الثالث الثانوي',
  gender: 'ذكر',
  school_name: 'السادات',
  parent_name: 'عبدالسلام خيري',
  course_name: 'العربي',
  date: new Date().toISOString(),
  unread: true
},
{
  id: 8,
  name: 'محمدي خيري',
  phone: '01021269329',
  email: 'm@m.com',
  image: { src: 'https://i.pravatar.cc/128?u=1' },
  grade_level: 'الصف الثالث الثانوي',
  gender: 'ذكر',
  school_name: 'السادات',
  parent_name: 'عبدالسلام خيري',
  course_name: 'العربي',
  date: new Date().toISOString(),
  unread: true
},
{
  id: 9,
  name: 'محمدي خيري',
  phone: '01021269329',
  email: 'm@m.com',
  image: { src: 'https://i.pravatar.cc/128?u=1' },
  grade_level: 'الصف الثالث الثانوي',
  gender: 'ذكر',
  school_name: 'السادات',
  parent_name: 'عبدالسلام خيري',
  course_name: 'العربي',
  date: new Date().toISOString()
}]

export default eventHandler(async () => {
  return mails
})
